import {defineType, defineField} from 'sanity'

// Singleton "Textes communs" : regroupe les blocs partages affiches sur toutes
// les pages du site (bloc d'appel final avant le pied de page, citation de la
// page d'accueil, et le pied de page lui-meme). Tous les champs sont editables
// par le client. Le site applique un repli sur ses textes d'origine en dur si
// un champ est laisse vide : aucun texte ne disparait jamais.
export default defineType({
  name: 'pageGlobale',
  title: 'Textes communs (CTA, pied de page)',
  type: 'document',
  groups: [
    {name: 'seuil', title: "Bloc d'appel final (Seuil)"},
    {name: 'antiCliches', title: 'Citation manifeste (accueil)'},
    {name: 'footer', title: 'Pied de page'},
  ],
  fields: [
    // BLOC D'APPEL FINAL (Seuil), affiche en bas de presque toutes les pages,
    // juste avant le pied de page.
    defineField({
      name: 'seuilSurtitre',
      title: 'Petit texte au-dessus du titre',
      description: "S'affiche dans le bloc d'appel final, en bas des pages, au-dessus du grand titre.",
      type: 'string',
      group: 'seuil',
      initialValue: 'Prêt à franchir le seuil',
    }),
    defineField({
      name: 'seuilTitre',
      title: 'Grand titre (premiere ligne)',
      description: "Premiere ligne du grand titre du bloc d'appel final.",
      type: 'string',
      group: 'seuil',
      initialValue: 'Encore une question,',
    }),
    defineField({
      name: 'seuilTitreItalique',
      title: 'Grand titre (deuxieme ligne, en italique)',
      description: 'Deuxieme ligne du grand titre, affichee en italique et en dore.',
      type: 'string',
      group: 'seuil',
      initialValue: 'ou prêt à réserver ?',
    }),
    defineField({
      name: 'seuilDescription',
      title: 'Texte sous le titre',
      description: "Paragraphe affiche sous le titre du bloc d'appel final.",
      type: 'text',
      rows: 3,
      group: 'seuil',
      initialValue:
        "Posez-moi votre question par email, ou réservez directement votre créneau. Vous êtes recontacté sous 24h pour confirmer, annulation possible jusqu'à 24h avant le rendez-vous.",
    }),
    defineField({
      name: 'seuilCtaReserver',
      title: 'Texte du bouton de reservation',
      description: 'Libelle du bouton dore qui mene vers la reservation.',
      type: 'string',
      group: 'seuil',
      initialValue: 'Réserver une consultation',
    }),
    defineField({
      name: 'seuilCtaQuestion',
      title: 'Texte du bouton de contact',
      description: 'Libelle du second bouton qui ouvre un email pour poser une question.',
      type: 'string',
      group: 'seuil',
      initialValue: 'Poser une question',
    }),
    defineField({
      name: 'seuilMention1',
      title: 'Mention de rassurance n1',
      description: "Premiere des trois petites mentions affichees sous les boutons.",
      type: 'string',
      group: 'seuil',
      initialValue: 'Paiement sécurisé par Stripe',
    }),
    defineField({
      name: 'seuilMention2',
      title: 'Mention de rassurance n2',
      description: 'Deuxieme des trois petites mentions affichees sous les boutons.',
      type: 'string',
      group: 'seuil',
      initialValue: 'Confirmation sous 24h',
    }),
    defineField({
      name: 'seuilMention3',
      title: 'Mention de rassurance n3',
      description: 'Troisieme des trois petites mentions affichees sous les boutons.',
      type: 'string',
      group: 'seuil',
      initialValue: 'Confidentialité absolue',
    }),

    // CITATION MANIFESTE, affichee sur la page d'accueil.
    defineField({
      name: 'antiClichesCitation',
      title: 'Citation (debut)',
      description: "Premiere partie de la citation manifeste affichee sur la page d'accueil.",
      type: 'text',
      rows: 3,
      group: 'antiCliches',
      initialValue: 'Je ne vends pas de rêves. Des faits vérifiables',
    }),
    defineField({
      name: 'antiClichesCitationItalique',
      title: 'Citation (partie en italique)',
      description: 'Partie de la citation affichee en italique et en dore, au milieu de la phrase.',
      type: 'string',
      group: 'antiCliches',
      initialValue: 'au moment même de la séance.',
    }),
    defineField({
      name: 'antiClichesSuite',
      title: 'Citation (fin)',
      description: 'Fin de la citation, affichee apres la partie en italique.',
      type: 'string',
      group: 'antiCliches',
      initialValue: 'Pas de sorts, pas de mise en scène, pas de dépendance.',
    }),
    defineField({
      name: 'antiClichesAuteur',
      title: 'Signature de la citation',
      description: 'Nom affiche sous la citation.',
      type: 'string',
      group: 'antiCliches',
      initialValue: 'Jocelyn Amir Swamy, Médium voyant',
    }),
    defineField({
      name: 'antiClichesCta1',
      title: 'Texte du bouton principal',
      description: 'Libelle du bouton dore sous la citation.',
      type: 'string',
      group: 'antiCliches',
      initialValue: 'Mon parcours',
    }),
    defineField({
      name: 'antiClichesCta2',
      title: 'Texte du bouton secondaire',
      description: 'Libelle du second bouton sous la citation.',
      type: 'string',
      group: 'antiCliches',
      initialValue: 'Prendre rendez-vous',
    }),

    // PIED DE PAGE, affiche en bas de toutes les pages.
    defineField({
      name: 'footerTitre',
      title: 'Nom affiche dans le pied de page',
      description: 'Nom affiche en gros a gauche du pied de page.',
      type: 'string',
      group: 'footer',
      initialValue: 'JOCELYN AMIR',
    }),
    defineField({
      name: 'footerDescription',
      title: 'Texte de presentation',
      description: 'Court paragraphe de presentation affiche dans le pied de page.',
      type: 'text',
      rows: 3,
      group: 'footer',
      initialValue:
        'Médium voyant à La Réunion. Clairvoyance, clairaudience, tirage de cartes et voyance sur photo. Au cabinet à Saint-Clotilde ou à distance.',
    }),
    defineField({
      name: 'footerContactTitre',
      title: 'Titre de la colonne contact',
      description: 'Titre de la colonne des coordonnees dans le pied de page.',
      type: 'string',
      group: 'footer',
      initialValue: 'Me contacter',
    }),
    defineField({
      name: 'footerVille',
      title: 'Ville',
      description: 'Ville affichee dans les coordonnees du pied de page.',
      type: 'string',
      group: 'footer',
      initialValue: 'Saint-Clotilde',
    }),
    defineField({
      name: 'footerRegion',
      title: 'Region',
      description: 'Region affichee sous la ville dans le pied de page.',
      type: 'string',
      group: 'footer',
      initialValue: 'La Réunion (974)',
    }),
    defineField({
      name: 'footerTelephone',
      title: 'Numero de telephone',
      description: 'Numero de telephone affiche dans le pied de page.',
      type: 'string',
      group: 'footer',
      initialValue: '+262 692 81 36 06',
    }),
    defineField({
      name: 'footerEmail',
      title: 'Adresse email',
      description: 'Adresse email affichee dans le pied de page.',
      type: 'string',
      group: 'footer',
      initialValue: 'contact@jocelynamir.com',
    }),
    defineField({
      name: 'footerRetrouveTitre',
      title: 'Titre de la colonne medias',
      description: 'Titre de la colonne ou on retrouve Jocelyn (TV, radio, reseaux).',
      type: 'string',
      group: 'footer',
      initialValue: 'On me retrouve',
    }),
    defineField({
      name: 'footerTv',
      title: 'Ligne television',
      description: 'Texte de la ligne television dans la colonne medias.',
      type: 'string',
      group: 'footer',
      initialValue: 'Télé Kreol, mercredis 19h30',
    }),
    defineField({
      name: 'footerRadio',
      title: 'Ligne radio',
      description: 'Texte de la ligne radio dans la colonne medias.',
      type: 'string',
      group: 'footer',
      initialValue: 'Kreol FM',
    }),
    defineField({
      name: 'footerSocial',
      title: 'Ligne reseau social',
      description: 'Texte du lien reseau social dans la colonne medias.',
      type: 'string',
      group: 'footer',
      initialValue: 'Facebook',
    }),
    defineField({
      name: 'footerCopyright',
      title: 'Ligne de copyright',
      description:
        "Ligne de copyright en bas du pied de page. Ecrivez {annee} la ou l'annee en cours doit apparaitre automatiquement.",
      type: 'string',
      group: 'footer',
      initialValue: '{annee} Jocelyn Amir. Tous droits réservés.',
    }),
    defineField({
      name: 'footerCredit',
      title: 'Ligne de credit du createur',
      description: 'Ligne tout en bas indiquant qui a cree le site.',
      type: 'string',
      group: 'footer',
      initialValue: 'Créé par Fondationstudio.fr',
    }),
  ],
  preview: {prepare: () => ({title: 'Textes communs (CTA, pied de page)'})},
})
