import {defineType, defineField, defineArrayMember} from 'sanity'

export default defineType({
  name: 'pageReserver',
  title: 'Page Reserver',
  type: 'document',
  groups: [
    {name: 'entete', title: 'En-tete'},
    {name: 'banniere', title: 'Banniere info'},
    {name: 'formules', title: 'Formules'},
    {name: 'regulieres', title: 'Seances regulieres'},
    {name: 'autre', title: 'Autre demande'},
    {name: 'footer', title: 'Note de bas de page'},
  ],
  fields: [
    defineField({
      name: 'surtitre',
      title: 'Surtitre de la page',
      type: 'string',
      group: 'entete',
      initialValue: 'Réservation en ligne',
    }),
    defineField({
      name: 'titre',
      title: 'Titre de la page',
      type: 'string',
      group: 'entete',
      initialValue: 'Choisissez votre formule.',
    }),
    defineField({
      name: 'titreItalique',
      title: 'Titre en italique',
      type: 'string',
      group: 'entete',
      initialValue: '',
    }),
    defineField({
      name: 'banniereTitre',
      title: 'Titre de la banniere info',
      type: 'string',
      group: 'banniere',
      initialValue: 'La réservation se fait exclusivement en ligne.',
    }),
    defineField({
      name: 'banniereTexte',
      title: 'Texte de la banniere info',
      type: 'text',
      rows: 3,
      group: 'banniere',
      initialValue:
        'Les messages et appels ne permettent pas de bloquer un créneau. Choisissez votre formule ci-dessous pour accéder au formulaire et au paiement sécurisé.',
    }),
    defineField({
      name: 'formules',
      title: 'Formules detaillees',
      description: 'Les deux formules de consultation reservables en ligne.',
      type: 'array',
      group: 'formules',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'surtitre', title: 'Surtitre', type: 'string'}),
            defineField({name: 'titre', title: 'Titre', type: 'string'}),
            defineField({name: 'description', title: 'Description', type: 'text', rows: 3}),
            defineField({
              name: 'features',
              title: 'Points inclus',
              type: 'array',
              of: [defineArrayMember({type: 'string'})],
            }),
            defineField({name: 'duree', title: 'Duree', type: 'string'}),
            defineField({name: 'prix', title: 'Prix (texte affiche)', type: 'string'}),
            defineField({name: 'labelCta', title: 'Texte du bouton', type: 'string'}),
          ],
          preview: {select: {title: 'titre', subtitle: 'duree'}},
        }),
      ],
      initialValue: [
        {
          surtitre: 'Au cabinet ou à distance',
          titre: 'Une heure',
          description:
            'Une heure complète, dans mon bureau zen à Saint-Clotilde ou à distance, au même tarif. Les quatre méthodes combinées sans précipitation.',
          features: [
            "Consultation d'une heure pleine, au cabinet ou à distance",
            'Quatre méthodes combinées en une séance',
            'Photos, courriers ou objets bienvenus',
            'Récap oral à la fin de la séance',
          ],
          duree: '1 heure',
          prix: '120',
          labelCta: 'Reserver en ligne',
        },
        {
          surtitre: 'Par téléphone, partout',
          titre: '30 minutes',
          description:
            "Trente minutes par téléphone, depuis La Réunion, l'Île Maurice, la métropole ou n'importe où.",
          features: [
            'Consultation de 30 minutes par téléphone uniquement',
            "Jocelyn vous appelle à l'heure du rendez-vous",
            'Mêmes méthodes que le cabinet, en condensé',
            'Aucun déplacement, où que vous soyez',
          ],
          duree: '30 minutes',
          prix: '85',
          labelCta: 'Reserver en ligne',
        },
      ],
    }),
    defineField({
      name: 'regulieresSurtitre',
      title: 'Surtitre (seances regulieres)',
      type: 'string',
      group: 'regulieres',
      initialValue: 'Suivi dans la durée',
    }),
    defineField({
      name: 'regulieresTitre',
      title: 'Titre (seances regulieres)',
      type: 'string',
      group: 'regulieres',
      initialValue: 'Séances régulières, tarif préférentiel',
    }),
    defineField({
      name: 'regulieresDescription',
      title: 'Texte (seances regulieres)',
      type: 'text',
      rows: 3,
      group: 'regulieres',
      initialValue:
        "Vous souhaitez consulter plusieurs fois dans l'année ? Un tarif préférentiel s'applique pour un accompagnement suivi, au cabinet ou à distance. Le détail se fait sur devis, selon votre rythme.",
    }),
    defineField({
      name: 'regulieresLabelCta',
      title: 'Texte du bouton (seances regulieres)',
      type: 'string',
      group: 'regulieres',
      initialValue: 'Demander un devis',
    }),
    defineField({
      name: 'autreSurtitre',
      title: 'Surtitre (autre demande)',
      type: 'string',
      group: 'autre',
      initialValue: 'Autre demande',
    }),
    defineField({
      name: 'autreTitre',
      title: 'Titre (autre demande)',
      type: 'string',
      group: 'autre',
      initialValue: 'Coaching de vie ou question spécifique ?',
    }),
    defineField({
      name: 'autreDescription',
      title: 'Texte (autre demande)',
      type: 'text',
      rows: 3,
      group: 'autre',
      initialValue:
        'Pour un accompagnement coaching, une question avant de réserver, ou toute autre demande, contactez directement Jocelyn.',
    }),
    defineField({
      name: 'autreLabelContact',
      title: 'Texte du bouton message',
      type: 'string',
      group: 'autre',
      initialValue: 'Envoyer un message',
    }),
    defineField({
      name: 'autreLabelTel',
      title: 'Texte du bouton appel',
      type: 'string',
      group: 'autre',
      initialValue: 'Appeler',
    }),
    defineField({
      name: 'noteFooter',
      title: 'Note de bas de page',
      type: 'text',
      rows: 2,
      group: 'footer',
      initialValue:
        "Paiement sécurisé. Après le règlement, vous êtes recontacté sous 24h pour confirmer votre rendez-vous. Annulation possible jusqu'à 24h avant.",
    }),
  ],
  preview: {prepare: () => ({title: 'Page Reserver'})},
})
